coll = set()
# print(type(coll))
coll.add(1)
coll.add(2)
coll.add(3)
coll.add(2)
coll.remove(1)
coll.add((9,5,7))
print(coll)
set2={5,3,"Ecokriti"}
print(coll.union(set2))
print(coll.intersection(set2))
# coll.clear()
# print(coll)
# print(len(coll))
# print(coll.pop())
# print(coll.pop())

a= ([7,9,9,5,3])
print(a)